### ISSUE TITLE
Epic C (requirement) Predict available harvest for any given day

### ISSUE THREAD

**Issue by ViklaSail** [StrawberryPick/Strawberry#24]
Need to estimate(predict) available crops amount for any given day during season. To that amount following is affecting and should be reflected as a task. 
General Formula of calculating free/available harvest for any given day: **harvest estimated - harvest reserved**

- [ ] #30
- [x] Age of the strawberry lines in question (we plant every year)
- [ ] Earlier seasons production curve aligned with current and given day. You have multiple seasons history
- [ ] Season start date
- [x] Calculated thermal sum for the current day
- [x] Weather prediction between this day and the given day
- [x] Harvesting history of season until current day
What data must we have to achieve above?
Going through other phases of data analytics?

**Comment by HerzogX** [comment]
We need to gather data from earlier seasons productions. When will we be able to interview our client again?
